"""added contact number

Revision ID: 0118e8a64fbd
Revises: e0f9b875c160
Create Date: 2022-03-24 09:40:14.848865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0118e8a64fbd'
down_revision = 'e0f9b875c160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('contact_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'contact_number')
    # ### end Alembic commands ###
