"""added properties

Revision ID: 0609b13b4537
Revises: 936656b1c79a
Create Date: 2022-03-17 09:43:00.949508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0609b13b4537'
down_revision = '936656b1c79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rules', sa.String(length=255), nullable=True),
    sa.Column('logos_url', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
