"""user enhanced

Revision ID: 1308b87fbd7c
Revises: 
Create Date: 2022-03-14 10:03:36.814638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1308b87fbd7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('yt_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    op.drop_column('match', 'yt_id')
    # ### end Alembic commands ###
