"""added logos and rules

Revision ID: 18ae07ea76db
Revises: 4bdd474bc20b
Create Date: 2022-03-17 10:01:37.268259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ae07ea76db'
down_revision = '4bdd474bc20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rules', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rules', sa.VARCHAR(length=255), nullable=True),
    sa.Column('logos_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rules')
    op.drop_table('logos')
    # ### end Alembic commands ###
