"""removed rule

Revision ID: 4bdd474bc20b
Revises: 0609b13b4537
Create Date: 2022-03-17 09:57:54.851248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdd474bc20b'
down_revision = '0609b13b4537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rules', sa.TEXT(), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
