"""added rules

Revision ID: 936656b1c79a
Revises: 1308b87fbd7c
Create Date: 2022-03-14 10:36:39.327266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936656b1c79a'
down_revision = '1308b87fbd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###
