"""removed max for season

Revision ID: 97f307d196a7
Revises: f5e4c1ed6431
Create Date: 2022-03-17 12:14:48.214599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f307d196a7'
down_revision = 'f5e4c1ed6431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season', 'max_teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('max_teams', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
