"""renamed logo to logo_url

Revision ID: efe89ece4199
Revises: 18ae07ea76db
Create Date: 2022-03-17 11:22:01.725641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe89ece4199'
down_revision = '18ae07ea76db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('logo_url', sa.String(length=255), nullable=True))
    op.drop_column('team', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('logo', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('team', 'logo_url')
    # ### end Alembic commands ###
